version: "{build}"

branches:
  only:
    - master

skip_tags: true
clone_folder: c:\projects\DisposeObject.c
clone_depth: 10

platform:
  - x86

build_script:
  - cd %APPVEYOR_BUILD_FOLDER%
  - call "C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\vcvarsall.bat" x86
  - msbuild DisposeObject.sln /p:Configuration=Release

test: off
deploy: off
artifacts:
  - path: Release\DisposeObject.exe
    name: DisposeObject.exe
